
package proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ReleveWebService", targetNamespace = "http://webService.enset.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReleveWebService {


    /**
     * 
     * @return
     *     returns proxy.ReleveService
     * @throws JAXBException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReleveService", targetNamespace = "http://webService.enset.ma/", className = "proxy.GetReleveService")
    @ResponseWrapper(localName = "getReleveServiceResponse", targetNamespace = "http://webService.enset.ma/", className = "proxy.GetReleveServiceResponse")
    @Action(input = "http://webService.enset.ma/ReleveWebService/getReleveServiceRequest", output = "http://webService.enset.ma/ReleveWebService/getReleveServiceResponse", fault = {
        @FaultAction(className = JAXBException_Exception.class, value = "http://webService.enset.ma/ReleveWebService/getReleveService/Fault/JAXBException")
    })
    public ReleveService getReleveService()
        throws JAXBException_Exception
    ;

}
