
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ReleveWebService", targetNamespace = "http://webService.enset.ma/", wsdlLocation = "http://localhost:9191/?wsdl")
public class ReleveWebService_Service
    extends Service
{

    private final static URL RELEVEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException RELEVEWEBSERVICE_EXCEPTION;
    private final static QName RELEVEWEBSERVICE_QNAME = new QName("http://webService.enset.ma/", "ReleveWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9191/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RELEVEWEBSERVICE_WSDL_LOCATION = url;
        RELEVEWEBSERVICE_EXCEPTION = e;
    }

    public ReleveWebService_Service() {
        super(__getWsdlLocation(), RELEVEWEBSERVICE_QNAME);
    }

    public ReleveWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RELEVEWEBSERVICE_QNAME, features);
    }

    public ReleveWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, RELEVEWEBSERVICE_QNAME);
    }

    public ReleveWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RELEVEWEBSERVICE_QNAME, features);
    }

    public ReleveWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReleveWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReleveWebService
     */
    @WebEndpoint(name = "ReleveWebServicePort")
    public ReleveWebService getReleveWebServicePort() {
        return super.getPort(new QName("http://webService.enset.ma/", "ReleveWebServicePort"), ReleveWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReleveWebService
     */
    @WebEndpoint(name = "ReleveWebServicePort")
    public ReleveWebService getReleveWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService.enset.ma/", "ReleveWebServicePort"), ReleveWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RELEVEWEBSERVICE_EXCEPTION!= null) {
            throw RELEVEWEBSERVICE_EXCEPTION;
        }
        return RELEVEWEBSERVICE_WSDL_LOCATION;
    }

}
